name: Scorecard Supply-Chain Security

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 0'  # Runs every Sunday at 01:30 UTC
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # for uploading results
      id-token: write  # for uploading results
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
